//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Zxxk.Dos.DataModel
{

	/// <summary>
	/// 实体类Answer 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("TX_Answer")]
	[Serializable]
	public partial class Answer : Entity 
	{
		#region Model
		private int _AnswerID;
		private int? _HomeWorkID;
		private string _OpenID;
		private int? _QuesID;
		private int? _QuesTypeID;
		private string _QuesAnswer;
		private string _StudentAnswer;
		private DateTime? _CommitDate;
		private int? _CategoryID;
		private string _CategoryName;
		private decimal? _Score;
		private int? _ParentQuesID;
		private int? _QuesNumber;
		private string _TencentID;
		private int? _OrderNumber;
		/// <summary>
		/// 
		/// </summary>
		public int AnswerID
		{
			get{ return _AnswerID; }
			set
			{
				this.OnPropertyValueChange(_.AnswerID,_AnswerID,value);
				this._AnswerID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? HomeWorkID
		{
			get{ return _HomeWorkID; }
			set
			{
				this.OnPropertyValueChange(_.HomeWorkID,_HomeWorkID,value);
				this._HomeWorkID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string OpenID
		{
			get{ return _OpenID; }
			set
			{
				this.OnPropertyValueChange(_.OpenID,_OpenID,value);
				this._OpenID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? QuesID
		{
			get{ return _QuesID; }
			set
			{
				this.OnPropertyValueChange(_.QuesID,_QuesID,value);
				this._QuesID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? QuesTypeID
		{
			get{ return _QuesTypeID; }
			set
			{
				this.OnPropertyValueChange(_.QuesTypeID,_QuesTypeID,value);
				this._QuesTypeID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string QuesAnswer
		{
			get{ return _QuesAnswer; }
			set
			{
				this.OnPropertyValueChange(_.QuesAnswer,_QuesAnswer,value);
				this._QuesAnswer=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string StudentAnswer
		{
			get{ return _StudentAnswer; }
			set
			{
				this.OnPropertyValueChange(_.StudentAnswer,_StudentAnswer,value);
				this._StudentAnswer=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CommitDate
		{
			get{ return _CommitDate; }
			set
			{
				this.OnPropertyValueChange(_.CommitDate,_CommitDate,value);
				this._CommitDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CategoryID
		{
			get{ return _CategoryID; }
			set
			{
				this.OnPropertyValueChange(_.CategoryID,_CategoryID,value);
				this._CategoryID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CategoryName
		{
			get{ return _CategoryName; }
			set
			{
				this.OnPropertyValueChange(_.CategoryName,_CategoryName,value);
				this._CategoryName=value;
			}
		}
		/// <summary>
		/// 学生得分
		/// </summary>
		public decimal? Score
		{
			get{ return _Score; }
			set
			{
				this.OnPropertyValueChange(_.Score,_Score,value);
				this._Score=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ParentQuesID
		{
			get{ return _ParentQuesID; }
			set
			{
				this.OnPropertyValueChange(_.ParentQuesID,_ParentQuesID,value);
				this._ParentQuesID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? QuesNumber
		{
			get{ return _QuesNumber; }
			set
			{
				this.OnPropertyValueChange(_.QuesNumber,_QuesNumber,value);
				this._QuesNumber=value;
			}
		}
		/// <summary>
		/// 腾讯ID 1001_2001_3001_4321
		/// </summary>
		public string TencentID
		{
			get{ return _TencentID; }
			set
			{
				this.OnPropertyValueChange(_.TencentID,_TencentID,value);
				this._TencentID=value;
			}
		}
		/// <summary>
		/// 试题顺序
		/// </summary>
		public int? OrderNumber
		{
			get{ return _OrderNumber; }
			set
			{
				this.OnPropertyValueChange(_.OrderNumber,_OrderNumber,value);
				this._OrderNumber=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.AnswerID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.AnswerID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.AnswerID,
				_.HomeWorkID,
				_.OpenID,
				_.QuesID,
				_.QuesTypeID,
				_.QuesAnswer,
				_.StudentAnswer,
				_.CommitDate,
				_.CategoryID,
				_.CategoryName,
				_.Score,
				_.ParentQuesID,
				_.QuesNumber,
				_.TencentID,
				_.OrderNumber};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._AnswerID,
				this._HomeWorkID,
				this._OpenID,
				this._QuesID,
				this._QuesTypeID,
				this._QuesAnswer,
				this._StudentAnswer,
				this._CommitDate,
				this._CategoryID,
				this._CategoryName,
				this._Score,
				this._ParentQuesID,
				this._QuesNumber,
				this._TencentID,
				this._OrderNumber};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","TX_Answer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AnswerID = new Field("AnswerID","TX_Answer","AnswerID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HomeWorkID = new Field("HomeWorkID","TX_Answer","HomeWorkID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OpenID = new Field("OpenID","TX_Answer","OpenID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QuesID = new Field("QuesID","TX_Answer","QuesID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QuesTypeID = new Field("QuesTypeID","TX_Answer","QuesTypeID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QuesAnswer = new Field("QuesAnswer","TX_Answer","QuesAnswer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StudentAnswer = new Field("StudentAnswer","TX_Answer","StudentAnswer");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CommitDate = new Field("CommitDate","TX_Answer","CommitDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CategoryID = new Field("CategoryID","TX_Answer","CategoryID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CategoryName = new Field("CategoryName","TX_Answer","CategoryName");
			/// <summary>
			/// 学生得分
			/// </summary>
			public readonly static Field Score = new Field("Score","TX_Answer","学生得分");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentQuesID = new Field("ParentQuesID","TX_Answer","ParentQuesID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field QuesNumber = new Field("QuesNumber","TX_Answer","QuesNumber");
			/// <summary>
			/// 腾讯ID 1001_2001_3001_4321
			/// </summary>
			public readonly static Field TencentID = new Field("TencentID","TX_Answer","腾讯ID 1001_2001_3001_4321");
			/// <summary>
			/// 试题顺序
			/// </summary>
			public readonly static Field OrderNumber = new Field("OrderNumber","TX_Answer","试题顺序");
		}
		#endregion


	}
}

